stages:
  - build
  - test

build:
  stage: build
  script:
    - make clean 
    - scala-cli compile .
  tags:
    - shell

test:
  stage: test
  script:
  #  - scala-cli test .
  tags:
    - shell


