stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - make clean 
    - make 
  tags:
    - shell

test:
  stage: test
  script:
   - echo "test"
  tags:
    - shell

deploy_vm:
  stage: deploy
  script:
    - tmux kill-session -t web || true
    - make clean
    - make 
    - export PORT=5001
    - tmux new-session -d -s web "echo deploying; ./wacc"
  tags:
    - shell

